directories:
  output: release
  buildResources: build
appId: com.example.my-knowledge-planner
productName: 知识计划
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
extraMetadata:
  main: src/main/main.js
electronVersion: 22.3.27
