directories:
  output: release
  buildResources: build
appId: com.example.planet
productName: Planet
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
extraMetadata:
  main: src/main/main.js
electronVersion: 22.3.27
